// 32 Irish Counties
const List<String> irishCounties = [
  'Antrim',
  'Armagh',
  'Carlow',
  'Cavan',
  'Clare',
  'Cork',
  'Derry',
  'Donegal',
  'Down',
  'Dublin',
  'Fermanagh',
  'Galway',
  'Kerry',
  'Kildare',
  'Kilkenny',
  'Laois',
  'Leitrim',
  'Limerick',
  'Longford',
  'Louth',
  'Mayo',
  'Meath',
  'Monaghan',
  'Offaly',
  'Roscommon',
  'Sligo',
  'Tipperary',
  'Tyrone',
  'Waterford',
  'Westmeath',
  'Wexford',
  'Wicklow',
];

// Mock county median prices (€/kg) - in production, fetch from Price Pulse
const Map<String, double> countyMedianPrices = {
  'Antrim': 4.15,
  'Armagh': 4.12,
  'Carlow': 4.18,
  'Cavan': 4.10,
  'Clare': 4.20,
  'Cork': 4.22,
  'Derry': 4.14,
  'Donegal': 4.08,
  'Down': 4.16,
  'Dublin': 4.25,
  'Fermanagh': 4.11,
  'Galway': 4.19,
  'Kerry': 4.21,
  'Kildare': 4.23,
  'Kilkenny': 4.17,
  'Laois': 4.15,
  'Leitrim': 4.09,
  'Limerick': 4.20,
  'Longford': 4.12,
  'Louth': 4.16,
  'Mayo': 4.13,
  'Meath': 4.18,
  'Monaghan': 4.11,
  'Offaly': 4.14,
  'Roscommon': 4.10,
  'Sligo': 4.12,
  'Tipperary': 4.19,
  'Tyrone': 4.13,
  'Waterford': 4.17,
  'Westmeath': 4.15,
  'Wexford': 4.18,
  'Wicklow': 4.20,
};
